[general]
live_config_reload = true
import = ["~/.config/alacritty/colors/gruvbox-dark-hard.toml"]

[font]
size = 10.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Shift"

[window]
decorations = "none"
opacity = 0.97

[window.dimensions]
columns = 130
lines = 40

[window.padding]
x = 5
y = 5
